### ISSUE TITLE
max length

### ISSUE THREAD

**Issue by YiyangLi** [futuweb/webpack-amdi18n-loader#13]
have you tried a file with massive messages, my message reaches the limit.

```
Unterminated string constant (1:372037)
You may need an appropriate loader to handle this file type.
SyntaxError: Unterminated string constant (1:372037)

```

Could you verify that? Thanks a lot!

**Comment by TooBug** [comment]
Can you provide an example? How large is the language file?

**Comment by YiyangLi** [comment]
the language file is about 500K, let me give you a snippet to generate a json with the size.

**Comment by YiyangLi** [comment]
```
function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
      .toString(16)
      .substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
    s4() + '-' + s4() + s4() + s4();
}

var bigLang = (function() {
  var root = {};
  for (var i = 0; i < 6144; i++) {root['key' + guid()] = guid();}
  return {root};
}());

```
I don't think it's your lib's problem, it's something related to the lib called acorn.js


```
[exec]     SyntaxError: Unterminated string constant (4191:40)
     [exec]         at Parser.pp$4.raise (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:2221:15)
     [exec]         at Parser.pp$7.readString (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:2938:35)
     [exec]         at Parser.pp$7.getTokenFromCode (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:2724:19)
     [exec]         at Parser.pp$7.readToken (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:2477:17)
     [exec]         at Parser.pp$7.nextToken (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:2468:15)
     [exec]         at Parser.pp$7.next (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:2413:10)
     [exec]         at Parser.pp.eat (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:536:12)
     [exec]         at Parser.pp$3.parsePropertyValue (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:1997:14)
     [exec]         at Parser.pp$3.parseObj (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:1989:14)
     [exec]         at Parser.pp$3.parseExprAtom (/Users/yiyangli/clients/admin/node_modules/acorn/dist/acorn.js:1805:19)

```

**Comment by TooBug** [comment]
Can you provide a short version of the language file?

Your code showed how to get the langage object, but didn’t show how to generate the language file.

**Comment by yiyangli-okta** [comment]
[lang_out.js.zip](https://github.com/futuweb/webpack-amdi18n-loader/files/1000200/lang_out.js.zip)
the zip file contains the language file I generated.

**Comment by TooBug** [comment]
I’ve tested this file, seems no problem. Can you provide the full code contains the problem?

**Comment by YiyangLi** [comment]
another files looks like this:

```
/* eslint max-params: [2, 8] */
define([
  'amdi18n!nls/messages',
  'amdi18n!nls/enduser',
  'amdi18n!nls/homepage',
  'amdi18n!nls/shared',
  'amdi18n!nls/selfservice',
  'amdi18n!nls/country'
], function (messages, enduser, homepage, shared, selfservice, country) {
  return {
    messages: messages.root || messages,
    enduser: enduser.root || enduser,
    homepage: homepage.root || homepage,
    shared: shared.root || shared,
    selfservice: selfservice.root || selfservice,
    country: country.root || country
  };
});
```

I simply run grunt webpack to pack this Bundles, and it doesn't work for me.

**Comment by YiyangLi** [comment]
[lang_out.js.zip](https://github.com/futuweb/webpack-amdi18n-loader/files/1000200/lang_out.js.zip)
the zip file contains the language file I generated.

**Comment by TooBug** [comment]
@YiyangLi Have you solved your problem?

I've tried your file, still no problem.

I'll close this issue now, If you still has problem, feel free to reopen it, and please tell me the detailed info, e.g the version of webpack, the full files that can reproduct this issue etc.
