### ISSUE TITLE
ReferenceError: process is not defined while bundling admi18n-loader

### ISSUE THREAD

**Issue by amalyala** [futuweb/webpack-amdi18n-loader#23]
I am trying to migrate my application using requirejs to webpack. The internationalization was done using requirejs i18n. Now I want to replace it with amdi18n-loader.

I am using amdi18n-loader exactly like specified in the README.md.  While bundling my webpack modules, error is thrown in amdi18n-loader

ReferenceError: process is not defined
    at register (evalmachine.<anonymous>:29:57)
    at evalmachine.<anonymous>:29:924
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at getJsonFromFile (/Users/amalyala/Documents/work/c3-clouds/node_modules/amdi18n-loader/index.js:74:12)
    at Object.module.exports (/Users/amalyala/Documents/work/c3-clouds/node_modules/amdi18n-loader/index.js:79:13)

because of the error, the lang.js is generated with
var amdi18n = {}; //i.e., empty object
instead of
var amdi18n={"__root":{"HELLO":"world"},"__zh-cn":{"HELLO":"你好"},"__zh-hk":{"HELLO":"雷吼"}}

I commented the vmScript.runInContext(context); inside index.js:74, but this wouldn't populate the amdi18n object correctly. The amdi18n.init() would run but since __root property is undefined inside amdi18n object, no language strings are loaded.

So clearly I shouldn't comment vmScript.runInContext(context) line. How do I fix this error?

**Comment by amalyala** [comment]
sorry, the issue is because of react-hot-loader. nothing related to amdi18n
