### ISSUE TITLE
ReferenceError: window is not defined running in Node

### ISSUE THREAD

**Issue by gitgrimbo** [futuweb/webpack-amdi18n-loader#26]
```
ReferenceError: window is not defined
  at Object.amdi18n.init  <node_modules\amdi18n-loader\index.js!..\webapp\scripts\nls\example.js:4:4>
  at eval  <node_modules\amdi18n-loader\index.js!..\webapp\scripts\nls\example.js:27:12>
  at Object.../node_modules/amdi18n-loader/index.js!../webapp/scripts/nls/example.js  <tests\unit.js:96:1>
  at __webpack_require__  <tests\unit.js:20:30>
  at eval  <webapp\scripts\preview\example.js:14:5>
  at Object.../webapp/scripts/preview/example.js  <tests\unit.js:413:1>
  at __webpack_require__  <tests\unit.js:20:30>
  at eval  <webapp\scripts\core\StatsService.js:8:5>
  at Object.../webapp/scripts/core/StatsService.js  <tests\unit.js:236:1>
  at __webpack_require__  <tests\unit.js:20:30>
```

This code seems to assume window exists:

```
	var init = function(language){
		// get the default language
		if(!language){
			if(window._i18n && window._i18n.locale){
				language = window._i18n.locale;
			}else if(document.documentElement.lang){
				language = document.documentElement.lang;
			}else{
				language = 'root';
			}
		}
```

How could a user pass in a language?

**Comment by TooBug** [comment]
The code assets after packaging by webpack & webpack-amdi18n-loader are used in client (browser) environment, which exists `window` object. According to your error log, seems you are using the code in Node environment.

So what is your code doing? Server side rendering or sth else? Please give more details.

**Comment by gitgrimbo** [comment]
Hi, I'm running tests using Intern on Node. I thought that the library might be able to run on both server and browser.

If that's not the case then I'll either exclude these tests from running on Node, or run the tests against a built bundle.

But it seems like the library could work with minor `typeof` tweaks.

```
			if(typeof window !== "undefined" && window._i18n && window._i18n.locale){
				language = window._i18n.locale;
			}else if(typeof document !== "undefined" && document.documentElement.lang){
				language = document.documentElement.lang;
			}else{
				language = 'root';
			}
```

**Comment by TooBug** [comment]
Yes, It's possible to support this, But no one use like this before, so I didn't consider it. Pull Request welcome.

**Comment by TooBug** [comment]
close via #27
